### ISSUE TITLE
RestAttributeDao . Why Override this method ?

### ISSUE THREAD

**Issue by Newbe36524** [apereo/person-directory#16]
https://github.com/apereo/person-directory/blob/6c57495bb3837038e53213b545e0ef4719247741/person-directory-impl/src/main/java/org/apereo/services/persondir/support/RestfulPersonAttributeDao.java#L121

why not just use super.metthod ,since it is not supported

**Comment by mmoayyed** [comment]
Start from here: https://github.com/apereo/person-directory/pulls and work your way up.
